// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcnP6yyuuX9IybWVkfB76MUForKS_lHnU',
    appId: '1:35075678219:web:00a16ed7ec956d26eca70e',
    messagingSenderId: '35075678219',
    projectId: 'qlsp-b75fc',
    authDomain: 'qlsp-b75fc.firebaseapp.com',
    storageBucket: 'qlsp-b75fc.firebasestorage.app',
    measurementId: 'G-B9EJZT9SR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWwO5AAcplbOKEiHNkhZ4wi9YRYz1mcs',
    appId: '1:35075678219:android:dfa736d6438206deeca70e',
    messagingSenderId: '35075678219',
    projectId: 'qlsp-b75fc',
    storageBucket: 'qlsp-b75fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZphI73YJun7KxskD7_1zpngvmE07ta4',
    appId: '1:35075678219:ios:914d91b4bfc69b4eeca70e',
    messagingSenderId: '35075678219',
    projectId: 'qlsp-b75fc',
    storageBucket: 'qlsp-b75fc.firebasestorage.app',
    iosBundleId: 'com.example.productManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZphI73YJun7KxskD7_1zpngvmE07ta4',
    appId: '1:35075678219:ios:914d91b4bfc69b4eeca70e',
    messagingSenderId: '35075678219',
    projectId: 'qlsp-b75fc',
    storageBucket: 'qlsp-b75fc.firebasestorage.app',
    iosBundleId: 'com.example.productManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcnP6yyuuX9IybWVkfB76MUForKS_lHnU',
    appId: '1:35075678219:web:db6d19d690575af5eca70e',
    messagingSenderId: '35075678219',
    projectId: 'qlsp-b75fc',
    authDomain: 'qlsp-b75fc.firebaseapp.com',
    storageBucket: 'qlsp-b75fc.firebasestorage.app',
    measurementId: 'G-ER6XR1QV33',
  );
}